name: rhythm
description: A pitch detection plugin for Flutter
version: 0.1.0
homepage: https://github.com/SaeedMasoumi/Rhythm

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^6.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: io.saeid.rhythm
        pluginClass: RhythmPlugin
      ios:
        pluginClass: RhythmPlugin